import type { ProviderWithDistance, Job, ServiceCategory } from "@/types/customer"

export const serviceCategories: ServiceCategory[] = [
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "🔧",
    description: "Pipe repairs, installations, and maintenance",
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "⚡",
    description: "Wiring, installations, and repairs",
  },
  {
    id: "cleaning",
    name: "Cleaning",
    icon: "🧹",
    description: "Home and office cleaning services",
  },
  {
    id: "painting",
    name: "Painting",
    icon: "🎨",
    description: "Interior and exterior painting",
  },
  {
    id: "carpentry",
    name: "Carpentry",
    icon: "🪚",
    description: "Furniture and structural carpentry",
  },
  {
    id: "landscaping",
    name: "Landscaping",
    icon: "🌱",
    description: "Garden design and maintenance",
  },
]

export const mockProviders: ProviderWithDistance[] = [
  {
    id: 1,
    provider_name: "John Plumber Pro",
    provider_phone: "+1-555-0101",
    provider_service: "Plumbing",
    provider_desc: "Expert plumber with 8 years of experience",
    provider_location_lat: 40.7128,
    provider_location_lon: -74.006,
    location_lat: 40.7128,
    location_lon: -74.006,
    rating: 4.8,
    completedJobs: 245,
  },
  {
    id: 2,
    provider_name: "Electric Eddie",
    provider_phone: "+1-555-0102",
    provider_service: "Electrical",
    provider_desc: "Licensed electrician, residential & commercial",
    provider_location_lat: 40.715,
    provider_location_lon: -74.003,
    location_lat: 40.715,
    location_lon: -74.003,
    rating: 4.9,
    completedJobs: 312,
  },
  {
    id: 3,
    provider_name: "Sparkle Clean Team",
    provider_phone: "+1-555-0103",
    provider_service: "Cleaning",
    provider_desc: "Professional cleaning with eco-friendly products",
    provider_location_lat: 40.72,
    provider_location_lon: -73.99,
    location_lat: 40.72,
    location_lon: -73.99,
    rating: 4.7,
    completedJobs: 189,
  },
  {
    id: 4,
    provider_name: "Paint Perfect",
    provider_phone: "+1-555-0104",
    provider_service: "Painting",
    provider_desc: "Custom painting solutions for every space",
    provider_location_lat: 40.73,
    provider_location_lon: -73.98,
    location_lat: 40.73,
    location_lon: -73.98,
    rating: 4.6,
    completedJobs: 156,
  },
  {
    id: 5,
    provider_name: "Woodcraft Wiz",
    provider_phone: "+1-555-0105",
    provider_service: "Carpentry",
    provider_desc: "Custom carpentry and furniture creation",
    provider_location_lat: 40.725,
    provider_location_lon: -74.01,
    location_lat: 40.725,
    location_lon: -74.01,
    rating: 4.9,
    completedJobs: 203,
  },
  {
    id: 6,
    provider_name: "Green Gardens",
    provider_phone: "+1-555-0106",
    provider_service: "Landscaping",
    provider_desc: "Beautiful outdoor spaces designed & maintained",
    provider_location_lat: 40.74,
    provider_location_lon: -73.97,
    location_lat: 40.74,
    location_lon: -73.97,
    rating: 4.8,
    completedJobs: 178,
  },
  {
    id: 7,
    provider_name: "Plumb Line Services",
    provider_phone: "+1-555-0107",
    provider_service: "Plumbing",
    provider_desc: "24/7 emergency plumbing services available",
    provider_location_lat: 40.71,
    provider_location_lon: -74.02,
    location_lat: 40.71,
    location_lon: -74.02,
    rating: 4.7,
    completedJobs: 267,
  },
  {
    id: 8,
    provider_name: "Bright Sparks Electric",
    provider_phone: "+1-555-0108",
    provider_service: "Electrical",
    provider_desc: "Solar installations and smart home upgrades",
    provider_location_lat: 40.735,
    provider_location_lon: -73.995,
    location_lat: 40.735,
    location_lon: -73.995,
    rating: 4.9,
    completedJobs: 234,
  },
]

export const mockJobs: Job[] = [
  {
    id: 1,
    customer_id: 101,
    customer_name: "Sarah Johnson",
    customer_phone: "+1-555-1001",
    customer_email: "sarah@example.com",
    service_type: "Plumbing",
    description: "Leaky kitchen faucet needs repair",
    location_lat: 40.7128,
    location_lon: -74.006,
    address: "123 Main St, New York, NY 10001",
    status: "pending",
    created_at: "2024-04-22T10:30:00Z",
    budget: 150,
    urgency: "high",
  },
  {
    id: 2,
    customer_id: 102,
    customer_name: "Mike Chen",
    customer_phone: "+1-555-1002",
    customer_email: "mike@example.com",
    service_type: "Electrical",
    description: "Install new ceiling fan in living room",
    location_lat: 40.715,
    location_lon: -74.003,
    address: "456 Park Ave, New York, NY 10022",
    status: "pending",
    created_at: "2024-04-22T09:15:00Z",
    budget: 250,
    urgency: "medium",
  },
  {
    id: 3,
    customer_id: 103,
    customer_name: "Emma Wilson",
    customer_phone: "+1-555-1003",
    customer_email: "emma@example.com",
    service_type: "Cleaning",
    description: "Deep clean apartment before moving in",
    location_lat: 40.72,
    location_lon: -73.99,
    address: "789 Broadway, New York, NY 10003",
    status: "pending",
    created_at: "2024-04-22T08:45:00Z",
    budget: 300,
    urgency: "high",
  },
  {
    id: 4,
    customer_id: 104,
    customer_name: "David Brown",
    customer_phone: "+1-555-1004",
    customer_email: "david@example.com",
    service_type: "Painting",
    description: "Paint bedroom walls in soft blue",
    location_lat: 40.73,
    location_lon: -73.98,
    address: "321 5th Ave, New York, NY 10016",
    status: "accepted",
    created_at: "2024-04-21T14:20:00Z",
    budget: 400,
    urgency: "low",
  },
  {
    id: 5,
    customer_id: 105,
    customer_name: "Lisa Martinez",
    customer_phone: "+1-555-1005",
    customer_email: "lisa@example.com",
    service_type: "Carpentry",
    description: "Build custom shelving unit for home office",
    location_lat: 40.725,
    location_lon: -74.01,
    address: "555 Madison Ave, New York, NY 10022",
    status: "pending",
    created_at: "2024-04-22T11:00:00Z",
    budget: 600,
    urgency: "medium",
  },
]
